### ISSUE TITLE
Add topic to filename when downloading JSON/HTML mindmaps

### ISSUE THREAD

**Issue by QuantumQuacken** [DynamicApproach/Website#17]
_Example:_ topic is "become a chef", join it with "markmap" so that the downloaded file's name is "markmap_become a chef.json".
Substituting whitespaces with underscores or dashes might be a good idea.

Thank you for this nice tool! Keep up the good work!

**Comment by DynamicApproach** [comment]
Thanks for the feedback! :) You can consider this now fixed
